BlogPersonal/urls.py
from django.contrib import admin
from django.urls import path, include 
from BlogPersonalApp.views import *
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BlogPersonalApp.urls')),
    path('mensajes/', include('Mensajeria.urls')),

]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BlogPersonalApp/urls.py
from django.urls import path    
from BlogPersonalApp.views import *
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path('', inicio, name= "inicio"),


    path('profile/', perfil, name= "perfil"),
    path('editarPerfil', editarPerfil, name="EditarPerfil"),

    
    path('blog/', blog, name= "blog"),
    path('crearPost/', crearPost, name= "crearPost"),
    
    


    path('aboutme/', aboutme, name= "aboutme"),
    

    #path('messages/', mensajes, name= "mensajes"),

    path('registro/', registro, name= "Registro"),
    path('login/', loginview, name= "Login"),
    path('logout/', LogoutView.as_view(), name= "logout"),
    path('<id>/', leerPost, name= "leerPost"),
    path('eliminarPost/<id>/', eliminarPost, name="eliminarPost"),
    path('editarPost/<id>/', editarPost, name="editarPost"),

    


    
]

Mensajeria/urls.py
from django.urls import path    
from Mensajeria.views import *
from django.contrib.auth.views import LogoutView

app_name = 'Mensajeria'

urlpatterns = [

path('mensajes/', mensajes, name= 'mensajes'),


]

urls.py
from django.urls import path    
from BlogPersonalApp.views import *
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path('', inicio, name= "inicio"),


    path('profile/', perfil, name= "perfil"),
    path('editarPerfil', editarPerfil, name="EditarPerfil"),

    
    path('blog/', blog, name= "blog"),
    path('crearPost/', crearPost, name= "crearPost"),
    
    


    path('aboutme/', aboutme, name= "aboutme"),
    

    path('messages/', mensajes, name= "mensajes"),

    path('registro/', registro, name= "Registro"),
    path('login/', loginview, name= "Login"),
    path('logout/', LogoutView.as_view(), name= "logout"),
    path('<subtitulo>/', leerPost, name= "leerPost"),

    


    
]

BlogPersonalApp/views.py
from django.shortcuts import render, HttpResponse

from .models import *
from BlogPersonalApp.forms import *
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.



def inicio(request):
    return render(request, 'BlogPersonalApp/inicio.html')

#-------------------------PERFIL-------------------------------
@login_required
def perfil(request):
    
    return render(request, 'BlogPersonalApp/perfil.html')

@login_required
def editarPerfil(request):
    usuario= request.user
    if request.method == 'POST':
        form = EditarPerfilForm(request.POST)
        if form.is_valid():
            info = form.cleaned_data
            usuario.email= info["email"]
            usuario.password1= info["password1"]
            usuario.password2 =info["password2"]
            usuario.first_name= info["first_name"]
            usuario.last_name= info["last_name"]
            usuario.save()
            return render(request, 'BlogPersonalApp/inicio.html', {"mensaje": "Usuario modificado"})
        else:
            return render(request, 'BlogPersonalApp/editarPerfil.html', {'form': form})
    else:
        form = EditarPerfilForm(instance= usuario)
        return render(request, 'BlogPersonalApp/editarPerfil.html', {'form': form, 'nombredeusuario': usuario.username})



"""def obtenerAvatar(request):
    lista= Avatar.objects.filter(user=request.user)
    if len(lista) != 0:
        avatar= lista[0].imagen.url
    else:
        avatar= '/media/avatars/defectoavatar.jpg'
    return avatar"""
 


#-----------------------------CRUD DEL BLOG-----------------------------------

#-----------------------------BLOG Y POSTEOS ---------------------------------
@login_required
def blog(request):
    posts= Post.objects.filter()
    return render(request, 'BlogPersonalApp/blog.html', {'posts': posts})

@login_required
def leerPost(request, id):
    post =  Post.objects.get(id= id)
    return render(request, 'BlogPersonalApp/leerPost.html', {'post': post})

@login_required
def crearPost(request):
    if request.method == 'POST':
        form = CrearPostForm(request.POST)
        if form.is_valid():
            info = form.cleaned_data
            post = Post ( 
            titulo = info['titulo'],
            subtitulo = info['subtitulo'],
            descripcion = info['descripcion'],
            contenido = info['contenido'],
            autor= info['autor'],
            
            img= info['img'],
            )
            post.save()
            return render(request, 'BlogPersonalApp/inicio.html')
        else: 
            return render(request, 'BlogPersonalApp/crearPost.html', {'form': form})
    else: 
        form = CrearPostForm()
        return render(request, 'BlogPersonalApp/crearPost.html', {'form': form})

@login_required

def eliminarPost(request, id):
    post= Post.objects.get(id=id)
    post.delete()
    posts = Post.objects.all()
    return render(request, 'BlogPersonalApp/blog.html', {'posts': posts})


@login_required
def editarPost(request, id):
    post = Post.objects.get(id=id)
    if request.method == 'POST': 
        form = CrearPostForm(request.POST)
        if form.is_valid():
            info= form.cleaned_data
            post.titulo= info["titulo"]
            post.subtitulo= info["subtitulo"]
            post.descripcion= info["descripcion"]
            post.contenido= info["contenido"]
            post.img= info["img"]
            post.save()
            posts= Post.objects.all()
            return render(request, 'BlogPersonalApp/blog.html', {'posts': posts})
        pass


    else:
        form= CrearPostForm(initial=
        {"titulo": post.titulo,
         "subtitulo": post.subtitulo,
         'descripcion': post.descripcion,
         'contenido': post.contenido,
         'autor': post.autor,
         'img': post.img
        })
        return render(request, 'BlogPersonalApp/editarPost.html', {'form': form, 'post': post})
        






def aboutme(request):
    return render(request, 'BlogPersonalApp/aboutme.html')



"""@login_required
def mensajes(request):
    return render (request, 'BlogPersonalApp/mensajes.html')"""



#-----------REGISTRO Y LOGIN------------

def registro(request):
    if request.method == 'POST':
        form= RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            username= form.cleaned_data.get("username")
            form.save()
            return render(request, 'BlogPersonalApp/inicio.html', {"mensaje": f"Usuario {username} creado correctamente"})
        else:
            return render(request, 'BlogPersonalApp/registro.html', {"form": form, "mensaje": "Error al crear usuario"})
    else:
        form= RegistrarUsuarioForm()
        return render(request, 'BlogPersonalApp/registro.html', {'form': form})


def loginview(request):
    if request.method== 'POST':
        form= AuthenticationForm(request, data= request.POST)
        if form.is_valid():
            info= form.cleaned_data
            usu= info["username"]
            clav=info["password"]
            usuario= authenticate(username=usu, password=clav)
            if usuario is not None: 
                login(request, usuario)
                return render(request, 'BlogPersonalApp/inicio.html', {"mensaje": f"Bienvenido, {usuario}, se ha logueado correctamente"})
            else:
                return render(request, 'BlogPersonalApp/login.html', {"form": form, "mensaje": "Usuario o contraseña incorrectos"})
        else:
            return render(request, 'BlogPersonalApp/login.html', {"form": form, "mensaje": "Usuario o contraseña incorrectos"})

    else: 
        form= AuthenticationForm()
        return render(request, 'BlogPersonalApp/login.html',{'form': form})








    

BlogPersonalApp/templates/BlogPersonalApp/blog.html
{% extends "BlogPersonalApp/padre.html" %}


{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>Blog </title>
    {% endblock %}
</head>
<body>


    {% block cambio %}
        <h1>Blog</h1>
        <br>
        <br>
        <h3><a href="{% url 'crearPost' %}">Crear Post</a></h3>
        <br>

        {% if posts %}
        {% for post in posts %}
            <div>
                <a href="{% url 'leerPost' post.id %}">
                    <h2>
                        {{ post.titulo}}
                    </h2>
                </a>
                    <h3>
                        {{post.subtitulo}}
                    </h3>
                
                <p>
                    Publicado por <strong>{{ post.autor }}</strong> 
                </p>
                <p> {{post.fecha}} </p>
                <a href="{% url 'editarPost' post.id %}" > Editar post</a>
                <a href="{% url 'eliminarPost' post.id %}" >Eliminar post</a>
                
            </div>
            <hr>
        {% endfor %}
        {% else %}
        <h1> No existen posts aún</h1>

        {% endif %}

    {% endblock %}
    
</body>
</html>

BlogPersonalApp/templates/BlogPersonalApp/editarPost.html
{% extends "BlogPersonalApp/padre.html" %}
{% load static %}

{% block title %}
<h1> Editar Post: {{ post.titulo }}</h1>
{% endblock %}

{% block cambio  %}
<form action="{% url 'editarPost' post.id %}" method="POST"> {% csrf_token %}
    <table>

        {{ form.as_table }}

    </table>

    <input type="submit" value="Guardar cambios">
{% endblock %}

BlogPersonalApp/templates/BlogPersonalApp/padre.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="widthodevice-width, shrink-to-fit=no" />
    
    <link rel="stylesheet" href="{% static 'BlogPersonalApp/css/styles.css' %}">

</head>
<body>
    <div class="container">
        
        <div class="navbar">
            <img src="../../static/BlogPersonalApp/images/python3.png" class="logo" alt="Main logo">
            

        
        <ul>
            <li><a  href="{% url 'inicio' %} "> Inicio</a></li>
            <li><a href="{% url 'blog' %}"> Blog </a></li>
            <li><a href="{% url 'aboutme' %}"> Sobre mi</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'perfil' %}"> Perfil </a></li>
            <li><a href="{% url 'Mensajeria:mensajes' %}"> Mensajes </a></li>
            <li><a class="btn btn-danger"  href="{% url 'logout' %}"> Logout</a></li>
            {% else %}
            <li><a href="{% url 'Registro' %}"> Registrarse</a></li>
            <li><a href="{% url 'Login' %}"> Login</a></li>
            {% endif %}
            


        </ul>
        
        </div>
        
{% block title %}
   
{% endblock title %}
{% block cambio %}
    

{% endblock cambio %} 

{%block imagen %}

{% endblock imagen %}
    
    <h2>{{mensaje}}</h2>
    </div>





</body>
</html>